server:
  port: 9292

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/clinic_patient
    username: root
    password:
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
